# NUMPY
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.
### What is a NumPy Array?
A NumPy array is a powerful data structure provided by the NumPy (Numerical Python) library. It is similar to a Python list but optimized for numerical computations, making it faster, more memory-efficient, and more convenient for mathematical operations.
#### Key Features of NumPy Arrays
* **Homogeneous Data** – All elements in a NumPy array must be of the same data type (e.g., integers, floats, etc.).

* **Faster than Lists** – NumPy arrays are optimized for speed and use less memory compared to Python lists.

* **Supports Multi-Dimensional Data** – You can create 1D (vectors), 2D (matrices), or ND (multi-dimensional) arrays.

* **Efficient Mathematical Operations** – Supports vectorized operations (e.g., element-wise addition, multiplication).

* **Convenient Indexing and Slicing** – Similar to Python lists but more powerful.

### Numpy Arrays Vs Python Sequences
* NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

* The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

* A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## How to import NumPy

In [10]:
import numpy as np

## Creating NumPy Arrays


**Creating an array from a list**  
By using array()
This function converts python lists or tuple into Numpy arrays.

In [39]:
# 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


**Multidimensional Array**

In [16]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
# 3D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array creation functions

- **np.arange**  
Creates an array with values within a specified range.

In [41]:
# Create an array with 3 integers, starting from the default integer 0.
np.arange(3)

array([0, 1, 2])

* **arange with reshape**   
Changes the shape of an array.

In [44]:
np.arange(16).reshape(2,2,2,2)


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

* **np.ones**  
Creates an array filled with ones

In [50]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- **np.zeros**   
  Creates an array filled with zeros

In [55]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

* **np.random**  
  Generates random numbers between 0 and 1.

In [58]:
np.random.random((3,4))

array([[0.80960024, 0.13064207, 0.99327487, 0.66032661],
       [0.7981267 , 0.10770004, 0.21406162, 0.72760439],
       [0.63620808, 0.28573679, 0.3767902 , 0.33044058]])

*  **np.linspace(start, stop, num=50)**   
Creates an array with evenly spaced values between a range.   
*Parameters*
* start: The starting value of the sequence
* stop: The ending value of the sequence
* num(optional): The number of samples to generate(default is 50)

In [66]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

* **np.identity**  
  Creates an identity matrix

In [69]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Array Attributes  
In NumPy, arrays have several important attributes that provide useful information about the structure and properties of the array. Here are the key attributes:

In [75]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

* **ndim**    
Returns the number of dimensions of array.


In [77]:
a2.ndim

2

* **shape**   
Returns a tuple representing the number of elements along each axis.

In [86]:
a3.shape

(2, 2, 2)

* **size**   
Returns the total number of elements in the array.

In [89]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


* **dtype**   
Returns the datatype of elements in the array.

In [93]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype) 

int32
float64
int32


* **itemsize**   
Returns the size(in bytes) of an element in the array.

In [98]:
a3.itemsize

4

### Changing Dataype
In NumPy, you can change the data type of an array using several methods

* **Using astype**   
  The .astype() method allows you to create a new array with the desired data type.

In [103]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

* **Using dtype**   
You can specify the desired data type when creating an array.

In [110]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)

float32


### Array Math Operations

* **Element-wise Operations**  
  NumPy performs operations element-by-element for arrays of the same shape.

In [114]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


* **Multiplying vector with a scalar (broadcasting)**
  

In [121]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1 ** 2)
print(a1+2)
print(a1-2)
print(a1*2)


[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [123]:
# relational
print(a2 == 15)
print(a2>15)
print(a2!=15)

[[False False False  True]
 [False False False False]
 [False False False False]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True False]
 [ True  True  True  True]
 [ True  True  True  True]]


* **Aggregate Functions**   
  NumPy provides functions to compute statistics across an array.

In [133]:
a1 = np.random.random((3,3))
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)      # (column-wise product)
print(np.sum(a))        #  (Sum of all elements)
print(np.sum(a, axis=0)) # (Column-wise sum)
print(np.max(a))        # 21 (max from all elements)
print(np.min(a, axis=0)) # [5 7 9] (Column-wise min)



15
15
5
1


In [135]:
# mean/median/std/var
print(np.mean(a))       # (Mean)
print(np.median(a))     # (Median)
print(np.std(a))        # (Standard deviation)
print(np.var(a))       # (Variance)


3.0
3.0
1.4142135623730951
2.0


In [137]:
# trigonomoetric functions
np.sin(a1)

array([[0.83721297, 0.4780622 , 0.42715734],
       [0.71052875, 0.03133344, 0.6929207 ],
       [0.69027195, 0.04835909, 0.78642379]])

In [139]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)   # Matrix Multiplication

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [141]:
# log and exponents
np.exp(a1)
np.log(a1)

array([[-0.00786394, -0.69625774, -0.81792497],
       [-0.23540677, -3.46290565, -0.26718421],
       [-0.27198612, -3.02871094, -0.09982279]])

In [143]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)  # same round and floor

array([[18.,  6., 28.],
       [83., 35., 15.]])

# Indexing and slicing 

## Indexing 

In [176]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

**Indexing in 1D array**     
Similar to Python lists, NumPy arrays use zero-based indexing.

In [178]:
print(arr[0])  # gives the first element.
print(arr[2])  
print(arr[-1]) # Negative indexing 

1.0
3.0
3.0


**2D array**


In [180]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [184]:
#Select element number 6 from the 2-D array using indices i, j and two sets of brackets
print(a2[1][2])
# Select element number 8 from the 2-D array, this time using i and j indexes in a single 
# set of brackets, separated by a comma
print(a2[1,2])

6
6


In [186]:
#select 11 from the 2-D array
a2[2,3]

11

In [188]:
#access 4 from 2-D array
a2[1,0]

4

**3-D Array**    
A 3D NumPy array is structured as multiple 2D matrices stacked together. Indexing in 3D follows the format:    
array[depth, row, column]
* depth refers to the index of the 2D matrix (the "layer" in the 3D array).
* row refers to the row index in the selected 2D matrix.
* column refers to the column index in the selected row.

In [194]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [196]:
# access 5 from the 3D array
a3[1,0,1]

5

In [200]:
# access 2 from the array
a3[0,1,0]

2

## Slicing

**Slicing in 1-D array**  
synatx is : array[start:stop:step]

In [203]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
# extract 2,3,4 from the array
a1[2:5]

array([2, 3, 4])

In [207]:
a1[2:5:2]

array([2, 4])

**Slicing in 2-D array**    
syntax is :  array[row_start:row_stop:row_step, col_start:col_stop:col_step]
* row_start:row_stop:row_step → Selects specific rows.
* col_start:col_stop:col_step → Selects specific columns.



In [215]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [217]:
#extract first row
a2[0,:]

array([0, 1, 2, 3])

In [219]:
#extraxt 3rd column
a2[:,2]

array([ 2,  6, 10])

In [221]:
#extract [[5 6]
#        [9 10]]
a2[1:,1:3]


array([[ 5,  6],
       [ 9, 10]])

In [225]:
#extract [[0 3]
#         [8 11]]
a2[: :2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [229]:
# #extract [[1 3]
#         [9 11]]
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [231]:
#extract [4,7]
a2[1,::3]

array([4, 7])

In [235]:
# #extract [[1 2 3]
#         [5 6 7]]
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

**Slicing in 3-D array**  
syntax is: array[depth_start:depth_stop:depth_step, row_start:row_stop:row_step, col_start:col_stop:col_step]

In [239]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [241]:
#extract middle 2D array
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [243]:
#extract first and last 2D array
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [245]:
#Extract [ 3,  4,  5]
a3[0,1,:]


array([3, 4, 5])

In [247]:
#extract [10, 13, 16]
a3[1,:,1]

array([10, 13, 16])

In [251]:
#extract[22, 23],
#      [25, 26]
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [257]:
# extract[[ 0,  2],
#       [18, 20]]

a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating on numpy array

### Element-wise Iteration (1D or flattened)


In [262]:
arr = np.array([1, 2, 3, 4])

for element in arr:
    print(element)

1
2
3
4


### Row-wise Iteration (2D array)

In [265]:
arr2d = np.array([[1, 2], [3, 4]])

for row in arr2d:
    print(row)

[1 2]
[3 4]


### Iterating over 3-D array

In [269]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


### Using np.nditer (General Element-wise Iteration)

In [272]:
for x in np.nditer(arr2d):
    print(x)

1
2
3
4


# Reshaping

In [ ]:
#reshaping
#above

### Transpose
Gives transpose of a matirx

In [279]:
np.transpose(a2)
#or
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Ravel
Converts given array to 1D

In [282]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking
stacking refers to joining multiple arrays along a new axis. Here are the most common ways to stack arrays

### np.stack()
Stacks arrays along a new axis.

In [291]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.stack((a, b))  # Default axis=0
print(result)
print(np.stack((a, b), axis=1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### np.hstack() – Horizontal stack
Joins arrays along columns (axis=1) for 2D arrays or end-to-end for 1D.

In [293]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

### np.vstack() – Vertical stack
Joins arrays along rows (axis=0).

In [297]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting
splitting refers to dividing an array into multiple sub-arrays. There are a few common functions for splitting arrays:

### np.hsplit() – Horizontal split (columns)
Only works on 2D arrays.

In [301]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [305]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

### np.vsplit() – Vertical split (rows)
Also for 2D arrays.

In [307]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [309]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]